#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@lucky[-1]
	add ucitrack lucky
	set ucitrack.@lucky[-1].init=lucky
	commit ucitrack
EOF

chmod +x /usr/bin/luckyarch
rm -f /tmp/luci-indexcache* 2>/dev/null
rm -f /tmp/luci-modulecache/* 2>/dev/null  # 针对OpenWrt 21.02+
rm -f /tmp/luci-indexcache
return 0