#!/bin/sh

# 定义清理函数
clean_up() {
    if [ -n "$(uci -q get lucky.@lucky[-1].config)" ]; then
        uci -q delete lucky.@lucky[-1].config >/dev/null 2>&1
    fi
}

# 注册退出时执行的函数
trap clean_up EXIT

[  -n "$(uci -q get lucky.@lucky[-1].configdir)" ] && exit 0

if [ -n "$(uci -q get lucky.@lucky[-1].enabled)" ]; then

    if [ -n "$(uci -q get lucky.@lucky[-1].configdir)" ]; then
        exit 0
    else
        config_path="$(uci -q get lucky.@lucky[-1].config)"
        if [ -n "$config_path" ]; then
            config_dir="$(dirname "$config_path")"
        else
            config_dir="/etc/config/lucky.daji"
        fi
        uci -q batch <<EOF >/dev/null
            set lucky.@lucky[-1].configdir=$config_dir
            commit
EOF
    fi
    
    exit 0
else
    touch /etc/config/lucky
    uci -q batch <<EOF >/dev/null
        add lucky lucky
        set lucky.@lucky[-1].enabled=1
        set lucky.@lucky[-1].logger=1
        set lucky.@lucky[-1].configdir=/etc/config/lucky.daji
        commit
EOF
fi
exit 0